In [135]:
import numpy as np
from math import sin, cos, radians

def _p3(t1, t2, t3):
    # convert the degree inputs
    # into radians
    t1= radians(t1)
    t2= radians(t2)
    t3= radians(t3)
    # Create T0,1 && T1,2 && T2,3
    # given the D-H Table derived/
    tr1 = np.matrix([
        [cos(t1), -sin(t1), 0, 0],
        [sin(t1), cos(t1), 0, 0],
        [0,0,1,0],
        [0,0,0,1]
    ])
    tr2 = np.matrix([
        [-cos(t2), sin(t2), 0, 0],
        [-sin(t2), -cos(t2), 0, 0],
        [0,0,1,0],
        [0,0,0,1]
    ])
    tr3 = np.matrix([
        [cos(t3), -sin(t3), 0, 50],
        [sin(t3), cos(t3), 0, 0],
        [0,0,1,0],
        [0,0,0,1]
    ])
    # return T0,3 by taking the dot 
    # product of each transformation frame
    return tr1 * tr2 * tr3

heel = _p3(-4.15, -38.3, -2.57)
toe = _p3(9.64, -19.9, 31.8)

print('heel: \n\n', heel, '\n')
print('toe: \n\n', toe, '\n')

# not too sure which d_heel + d_toe values
# to use
# d_heel = np.matrix([[0], [-5], [0], [0]])
# d_toe = np.matrix([[0], [15], [0], [0]])
d_heel = np.matrix([
    [1,0,0,0],
    [0,1,0,5],
    [0,0,1,0],
    [0,0,0,1]
])
d_toe = np.matrix([
    [1,0,0,0],
    [0,1,0,-15],
    [0,0,1,0],
    [0,0,0,1]
])

p_heel = heel * d_heel
p_toe = toe * d_toe

print('position heel: \n\n', p_heel, '\n')
print('position toe: \n\n', p_toe, '\n')

print(p_heel[(1,0)] - p_toe[(1,0)])

heel: 

 [[ -0.70685991  -0.70735356   0.         -36.89333098]
 [  0.70735356  -0.70685991   0.          33.74732773]
 [  0.           0.           1.           0.        ]
 [  0.           0.           0.           1.        ]] 

toe: 

 [[ -0.93016148   0.36715069   0.         -49.20048128]
 [ -0.36715069  -0.93016148   0.           8.90576451]
 [  0.           0.           1.           0.        ]
 [  0.           0.           0.           1.        ]] 

position heel: 

 [[ -0.70685991  -0.70735356   0.         -40.43009881]
 [  0.70735356  -0.70685991   0.          30.21302817]
 [  0.           0.           1.           0.        ]
 [  0.           0.           0.           1.        ]] 

position toe: 

 [[ -0.93016148   0.36715069   0.         -54.70774165]
 [ -0.36715069  -0.93016148   0.          22.85818664]
 [  0.           0.           1.           0.        ]
 [  0.           0.           0.           1.        ]] 

1.0745042562886222
